feat:arm修改

diff --git a/Dockerfile_arm64 b/Dockerfile_arm64
--- a/Dockerfile_arm64
+++ b/Dockerfile_arm64
@@ -226,19 +226,23 @@ RUN cd /usr/local/src/freeswitch \
     && make install
 
 FROM base-cmake AS mod-audio-stream
+ARG CACHEBUST=1
 COPY --from=freeswitch /usr/local/freeswitch/ /usr/local/freeswitch/
 WORKDIR /usr/local/src
 ENV PKG_CONFIG_PATH=/usr/local/freeswitch/lib/pkgconfig:$PKG_CONFIG_PATH
-RUN git clone --depth 1 -b v1.0.3 https://github.com/amigniter/mod_audio_stream.git \
+RUN echo "Cache bust: $CACHEBUST" \
+    && git clone https://github.com/ethan-wind/mod_audio_stream.git \
     && cd mod_audio_stream \
     && git submodule update --init --recursive \
     && mkdir -p build && cd build \
     && cmake -DCMAKE_BUILD_TYPE=Release .. \
     && make -j ${BUILD_CPUS} \
-    && make install
+    && make install \
+    && echo "Checking installed module:" \
+    && ls -la /usr/local/freeswitch/mod/ | grep audio || echo "Module not found in /usr/local/freeswitch/mod/"
 
 FROM freeswitch AS freeswitch-final
-COPY --from=mod-audio-stream /usr/local/freeswitch/mod/ /usr/local/freeswitch/mod/
+COPY --from=mod-audio-stream /usr/local/freeswitch/mod/mod_audio_stream.so /usr/local/freeswitch/mod/
 RUN cd /usr/local/src/freeswitch \
     && cp /tmp/acl.conf.xml /usr/local/freeswitch/conf/autoload_configs \
     && cp /tmp/event_socket.conf.xml /usr/local/freeswitch/conf/autoload_configs \
@@ -257,7 +261,6 @@ ARG TARGETARCH
 COPY --from=freeswitch-final /usr/local/freeswitch/ /usr/local/freeswitch/
 COPY --from=freeswitch-final /usr/local/bin/ /usr/local/bin/
 COPY --from=freeswitch-final /usr/local/lib/ /usr/local/lib/
-COPY --from=freeswitch-final /usr/lib/aarch64-linux-gnu/ /usr/lib/aarch64-linux-gnu/
 RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list \
     && sed -i 's/security.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list \
     && apt update && apt install -y --quiet --no-install-recommends ca-certificates libsqlite3-0 libcurl4 libpcre3 libspeex1 libspeexdsp1 libedit2 libtiff5 libopus0 libsndfile1 libshout3 \
